In [16]:
import torch
from torch import nn
import numpy as np

In [2]:
gru1 = nn.GRU(2, 4, 1, batch_first=True)
gru_test_input = torch.zeros([1,3,2])+0.5
gru1_output = gru1(gru_test_input)

In [3]:
gru1_output

(tensor([[[-0.3352, -0.0475, -0.0508,  0.0806],
          [-0.3978, -0.0550, -0.0398,  0.0720],
          [-0.4103, -0.0571, -0.0257,  0.0596]]], grad_fn=<TransposeBackward1>),
 tensor([[[-0.4103, -0.0571, -0.0257,  0.0596]]], grad_fn=<StackBackward>))

In [44]:
gru1.bias_ih_l0.data.fill_(0)
gru1.bias_hh_l0.data.fill_(0)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
gru1_output = gru1(gru_test_input)
gru1_output[0].shape

torch.Size([1, 3, 4])

In [32]:
if isinstance(gru1,nn.GRU):
    print('y')

y


In [5]:
gru1.weight_ih_l0.shape

torch.Size([12, 2])

In [14]:
def convert_gru_input_kernel(kernel):
    kernel_r, kernel_z, kernel_h = np.vsplit(kernel, 3)
    kernels = [kernel_z, kernel_r, kernel_h]
    return torch.tensor(np.hstack([k.reshape(k.T.shape) for k in kernels]))

def convert_gru_recurrent_kernel(kernel):
    kernel_r, kernel_z, kernel_h = np.vsplit(kernel, 3)
    kernels = [kernel_z, kernel_r, kernel_h]
    return torch.tensor(np.hstack(kernels))

In [18]:
new_weight_ih_l0 = convert_gru_input_kernel(gru1.weight_ih_l0.detach().numpy())
print(new_weight_ih_l0.shape)

torch.Size([2, 12])


In [6]:
import keras
import tensorflow
from keras import layers

In [13]:
keras_conv1 = layers.Conv1D(3, 2, padding='same', activation='tanh', name='feature_conv1')

In [14]:
input_shape = (1,3,4)
x = tensorflow.random.normal(input_shape)
y = keras_conv1(x)

In [15]:
weights =  keras_conv1.get_weights()

In [16]:
weights[0].shape
#input 1
#kernal_size 0
#output 2

(2, 4, 3)

In [17]:
weights[1].shape

(3,)

In [7]:
keras_gru1 = layers.GRU(4,return_sequences=True, recurrent_activation="sigmoid", reset_after='true', name='gru_a',)
input_shape = (1,3,2)
x = tensorflow.random.normal(input_shape)
y = keras_gru1(x)

In [13]:
weights =  keras_gru1.get_weights()
weights[0].shape

(2, 12)

In [12]:
print(weights[1])

[[ 0.50630426 -0.18125176 -0.22455446 -0.22690475 -0.21649115 -0.19073492
  -0.01370192 -0.47307855  0.05561786  0.21302928  0.0155199   0.50292975]
 [-0.05305615  0.01354556  0.02428324 -0.10544971  0.5824456   0.23123857
   0.18460734 -0.3195278  -0.5989489  -0.13466732 -0.20463274  0.19403724]
 [-0.03756262  0.24331398 -0.7099939  -0.00343641  0.21649931 -0.02412327
  -0.04613936 -0.11119071 -0.07995344  0.18405285  0.4935046  -0.2992046 ]
 [ 0.30607358  0.029637   -0.01524288 -0.06086059  0.20136751 -0.4949669
  -0.19576669 -0.22203046  0.10759834 -0.52205724 -0.24321698 -0.4301926 ]]


In [19]:
y.shape

TensorShape([1, 3, 4])