In [3]:
import torch
from torch import nn

In [4]:
conv1 = nn.Conv1d(2, 3, 3 , stride=1, padding=1)
test_input = torch.zeros([1,2,3])+0.5

In [5]:
conv1.weight.size()
#input 1
#kernal_size 2
#output 0

torch.Size([3, 2, 3])

In [6]:
conv1.weight.permute(2,1,0).size()

torch.Size([3, 2, 3])

In [7]:
conv1.bias.size()

torch.Size([3])

In [8]:
conv1(test_input).size()

torch.Size([1, 3, 3])

In [33]:
gru1 = nn.GRU(2, 4, 1, batch_first=True)
gru_test_input = torch.zeros([1,3,2])+0.5
gru1_output = gru1(gru_test_input)

In [34]:
gru1_output

(tensor([[[ 0.1663,  0.0319, -0.1647, -0.0005],
          [ 0.2639, -0.0034, -0.2531,  0.0054],
          [ 0.3241, -0.0524, -0.2989,  0.0161]]], grad_fn=<TransposeBackward1>),
 tensor([[[ 0.3241, -0.0524, -0.2989,  0.0161]]], grad_fn=<StackBackward>))

In [44]:
gru1.bias_ih_l0.data.fill_(0)
gru1.bias_hh_l0.data.fill_(0)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [47]:
gru1_output = gru1(gru_test_input)
gru1_output

(tensor([[[ 0.1151,  0.1326, -0.1162,  0.1244],
          [ 0.1718,  0.2026, -0.1841,  0.1925],
          [ 0.1984,  0.2380, -0.2226,  0.2310]]], grad_fn=<TransposeBackward1>),
 tensor([[[ 0.1984,  0.2380, -0.2226,  0.2310]]], grad_fn=<StackBackward>))

In [32]:
if isinstance(gru1,nn.GRU):
    print('y')

y


In [11]:
gru1.weight_ih_l0

Parameter containing:
tensor([[-0.4915, -0.2800],
        [ 0.1494,  0.4230],
        [ 0.1987, -0.1954],
        [-0.2430,  0.5576],
        [ 0.1902,  0.0045],
        [-0.1755,  0.3100],
        [ 0.3749,  0.1937],
        [ 0.4891, -0.5212],
        [ 0.2451, -0.1316]], requires_grad=True)

In [12]:
import keras
import tensorflow
from keras import layers

In [13]:
keras_conv1 = layers.Conv1D(3, 2, padding='same', activation='tanh', name='feature_conv1')

In [14]:
input_shape = (1,3,4)
x = tensorflow.random.normal(input_shape)
y = keras_conv1(x)

In [15]:
weights =  keras_conv1.get_weights()

In [16]:
weights[0].shape
#input 1
#kernal_size 0
#output 2

(2, 4, 3)

In [17]:
weights[1].shape

(3,)

In [28]:
keras_gru1 = layers.GRU(4,return_sequences=True, recurrent_activation="sigmoid", reset_after='true', name='gru_a',)
input_shape = (1,3,2)
x = tensorflow.random.normal(input_shape)
y = keras_gru1(x)

In [29]:
weights =  keras_gru1.get_weights()
y.shape

TensorShape([1, 3, 4])